test_stdout!(
    errors_with_reason_and_arguments,
    "{caught, error, {reason, [1, 2]}}\n"
);
