test_stdout!(errors_with_reason, "{caught, error, reason}\n");
